# standard jekyll configuration
title: irie.yard
url: "https://solomonic.github.io"
name: Duppy conqueror in the digital jungle.
baseurl: ""

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# custom variables
email: info@rasta.online
avatar: "http://rasta.online/images/avatar.png"
description: Interested in ital living and organic farming? Join a Rasta Rootsman on the journey to real Rasta Livety.
skype: al0b4r
fb-user: www.rasta.online
fb-url: "https://www.facebook.com/www.rasta.online"
fb-app-id: 172683489748870
git-url: "https://github.com/Solomonic"
jekyll_doc: "http://jekyllrb.com/docs"

#set defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      share: rasta
